## Investigating the numpy.random package in Python

![numpy.jpg](numpy.jpg)
[NumPy](http://www.numpy.org/) (which stands for Numerical Python) is a library for the Python programming language, that adds support for huge multi-dimensional arrays and matrices of data. It also provides a large collection of high-level mathematical functions to operate on these arrays. It is an open source project and free to import. 

Randomly generated data is important in [various kinds of statistical research as well as aspects of computer science such as simulation and cryptography](https://en.wikipedia.org/wiki/Random_number_generation) and other areas where unpredictable results are necessary. 

[numpy.random](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html) is a submodule of the NumPy package that is used to generate random (or indeed, pseudorandom) numbers, using  an algorithm called the [Mersenne Twister](https://en.wikipedia.org/wiki/Mersenne_Twister), a pseudorandom number generator (PRNG).  This means that numpy.random does not generate numbers that are random in the *truest* sense of the term, rather it's sequence is based on random seed generation, which I'll discuss later in this assignment. 



## Simple random data
I decided to try out the various functions as part of the numpy.random submodule to see if running and testing them could help me to understand what each of them does. I found a [blog post](http://www.learningaboutelectronics.com/Articles/How-to-create-an-array-of-random-integers-in-Python-with-numpy.php) that began with an introduction to the submodule and how to create an array of random integers (an array being...)

In [1]:
import numpy as np
#creates an array of 5 random integers from 1 too 100
test1 = np.random.randint(1,101,5)
print (test1)

[61 65 31 80 74]


Using this blog's suggested array as a basis for further testing, I listed through the rest of the commands in the Simple Random Data *category* as follows:

In [2]:
test2 = np.random.randn(1,101,5)
print (test2)

test3 = np.random.randint(1, 101,5)
print (test3)

#the function np.random.integers has been deprecated and replaced with the above np.random.randint

[[[-2.31017967e+00  1.55077370e-04  3.11560926e-01 -1.92898024e+00
    1.79348471e-01]
  [-1.24830335e+00 -5.01863297e-01 -1.25676753e+00 -5.89568596e-02
   -7.61345749e-01]
  [ 5.13733276e-01 -1.52107336e+00  1.11705229e-01 -4.40908291e-01
   -3.59338705e-01]
  [-1.80564426e-01  4.88055225e-02 -1.36550576e+00  3.56832945e-01
   -1.56057248e+00]
  [ 5.33609907e-01 -6.98988149e-01 -4.19795402e-01  8.95294042e-01
    4.81439678e-01]
  [-1.32257694e+00  4.00294583e-01  1.16814405e+00 -1.70538510e+00
   -1.31437787e+00]
  [ 5.87915228e-01 -2.42709661e-01 -9.17509156e-01  1.65321827e+00
   -1.21093247e+00]
  [ 1.04679186e+00 -9.90098138e-01 -1.15773831e+00 -2.96104144e-01
   -4.30789777e-01]
  [-1.31629959e+00 -2.55399260e-01  1.09516146e+00 -7.22811243e-01
   -1.83163304e+00]
  [-2.69602520e-03  1.52306382e+00  1.13281618e+00  4.37586174e-01
   -3.96131280e-01]
  [ 1.89518202e-01 -1.21159166e+00 -8.24324114e-01  1.08122183e+00
   -1.42731400e+00]
  [ 9.87082592e-01  4.14044590e-01  7.82202

## Permutations
The Permutations functions of numpy.random are [shuffle(x)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.shuffle.html) and [permutation(x)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.permutation.html#numpy.random.permutation).  

Both of these functions relate to re-arranging provided random data. The shuffle(x) function shuffles data on the first axis of a multi-dimensional array, where the order of sub-arrays is changed but the contents remain the same:

### 1D Array

In [3]:
#example from https://www.science-emergence.com/Articles/How-to-randomly-shuffle-an-array-in-python-using-numpy/ 
import numpy as np
M = np.array([4,8,15,16,23,42])
np.random.shuffle(M)
M

array([16, 42,  8,  4, 15, 23])

### 2D Array

In [4]:
#example from https://www.science-emergence.com/Articles/How-to-randomly-shuffle-an-array-in-python-using-numpy/ 
import numpy as np
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.random.shuffle(M)
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

As you can see above, the sequence that the sets are displayed in has been shuffled, but the contents inside the brackets have remained in the same order.

The permutation(x) function however, when given an array, takes a copy and shuffles the elements randomly. 

In [5]:
#example using an array from https://www.w3cschool.cn/doc_numpy_1_10/numpy_1_10-generated-numpy-random-permutation.html
import numpy as np
array = np.random.permutation([1, 4, 9, 12, 15])
array

array([12,  1, 15,  4,  9])

In the case of an integer, the permutation function randomly permutes it's range:

In [6]:
#example using an integer 
import numpy as np
integer = np.random.permutation(8)
integer

array([6, 2, 1, 7, 3, 5, 4, 0])