## Investigating the numpy.random package in Python

![numpy.jpg](numpy.jpg)
[NumPy](http://www.numpy.org/) (which stands for Numerical Python) is a library for the Python programming language, that adds support for huge multi-dimensional arrays and matrices of data. It also provides a large collection of high-level mathematical functions to operate on these arrays. It is an open source project and free to import. 

Randomly generated data is important in [various kinds of statistical research as well as aspects of computer science such as simulation and cryptography](https://en.wikipedia.org/wiki/Random_number_generation) and other areas where unpredictable results are necessary. 

[numpy.random](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html) is a submodule of the NumPy package that is used to generate random (or indeed, pseudorandom) numbers, using  an algorithm called the [Mersenne Twister](https://en.wikipedia.org/wiki/Mersenne_Twister), a pseudorandom number generator (PRNG).  This means that numpy.random does not generate numbers that are random in the *truest* sense of the term, rather it's sequence is based on random seed generation, which I'll discuss later in this assignment. 



## Simple random data
I decided to try out the various functions as part of the numpy.random submodule to see if running and testing them could help me to understand what each of them does. I found a [blog post](http://www.learningaboutelectronics.com/Articles/How-to-create-an-array-of-random-integers-in-Python-with-numpy.php) that began with an introduction to the submodule and how to create an array of random integers (an array being...)

In [2]:
import numpy as np
#creates an array of 5 random integers from 1 too 100
test1 = np.random.randint(1,101,5)
print (test1)

[51 70 45 58 36]


Using this blog's suggested array as a basis for further testing, I listed through the rest of the commands in the Simple Random Data *category* as follows:

In [5]:
test2 = np.random.randn(1,101,5)
print (test2)

test3 = np.random.randint(1, 101,5)
print (test3)

#the function np.random.integers has been deprecated and replaced with the above np.random.randint

[[[-7.83606606e-03 -6.31017680e-01 -5.99908803e-01 -1.92780780e-01
   -3.70033933e-01]
  [ 9.56103059e-01  2.10247378e+00 -1.77804747e-01  3.04084065e-01
    8.82791483e-01]
  [-4.08216649e-02 -3.20336066e-01 -6.20156188e-01 -7.86898225e-01
   -1.75988650e+00]
  [-1.05812319e-01  4.23708725e-01  1.50330007e+00  2.64100877e+00
    7.39213148e-01]
  [ 1.41883606e+00  7.24261001e-01 -1.52367355e+00  7.32188307e-01
    2.06313394e-01]
  [-6.12459180e-01 -9.63189409e-01  1.80818869e-01 -5.73736448e-01
    9.48165651e-01]
  [ 2.88216743e-01  1.01381822e+00 -5.06603114e-01 -3.88426332e-01
    1.08979017e+00]
  [ 9.01635519e-01  1.12789357e-01  4.71872474e-01 -4.98589087e-01
    2.62659702e+00]
  [-1.02636760e+00  4.48812448e-01  2.37126210e-01  4.19087216e-01
    1.69870103e+00]
  [-7.95674635e-01  9.98728079e-03  9.93080564e-01  3.96063950e-01
    1.05935790e+00]
  [ 6.42921470e-01  9.99941282e-01  1.45372761e+00 -1.37773885e+00
    8.33830526e-01]
  [-2.03787338e+00 -4.21719328e-01  5.93819

## Permutations
The Permutations functions of numpy.random are [shuffle(x)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.shuffle.html) and permutation(x).  

Both of these functions relate to re-arranging provided random data, the shuffle(x) function shuffles data on the first axis of a multi-dimensional array, where the order of sub-arrays is changed but the contents remain the same:

### 1D Array

In [6]:
#example from https://www.science-emergence.com/Articles/How-to-randomly-shuffle-an-array-in-python-using-numpy/ 
import numpy as np
M = np.array([4,8,15,16,23,42])
np.random.shuffle(M)
M

array([ 4, 15,  8, 42, 23, 16])

### 2D Array

In [7]:
#example from https://www.science-emergence.com/Articles/How-to-randomly-shuffle-an-array-in-python-using-numpy/ 
import numpy as np
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.random.shuffle(M)
M

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

As you can see above, the sequence that the sets are displayed in has been shuffled, but the contents inside the brackets have remained in the same order.

The permutations(x) function 