## Investigating the numpy.random package

![numpy.jpg](numpy.jpg)
[NumPy](http://www.numpy.org/) (which stands for Numerical Python) is a library for the Python programming language, that adds support for huge multi-dimensional arrays and matrices of numbers. It also provides a large collection of high-level mathematical functions to operate on these arrays, and executes much faster than standard Python for this. It is an open source project and free to import, generally labelled in code as "np". It is part of the [SciPy](https://scipy.org/) ecosystem for Python, which also includes such libraries as pandas and matplotlib.

Randomly generated data is important in [various kinds of statistical research as well as aspects of computer science such as simulation and cryptography](https://en.wikipedia.org/wiki/Random_number_generation) and other areas where unpredictable results are necessary, for example, lottery-gaming, draws, slot machines and gambling in general. 

[numpy.random](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html) is a submodule of the NumPy package that is used to generate random (or indeed, pseudorandom) numbers, using  an algorithm called the [Mersenne Twister](https://en.wikipedia.org/wiki/Mersenne_Twister), a pseudorandom number generator (PRNG).  This means that numpy.random can provide numbers that appear to be unpredicted and indetermined, but that it actually does not generate numbers that are random in the *truest* sense of the term, rather it's sequence is based on random seed generation, which I'll discuss later in this assignment. 



## Simple random data
I decided to try out the various functions that are part of the numpy.random submodule to see if running and testing them could help me to understand what each of them does. The first function in the list is random.rand, which according to the NumPy manual will [create an array of the given shape and populate it with random samples](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html#numpy.random.rand) from a uniform distribution over [0,1)] I understand this to mean that this function will display an array (which is almost like a table or database, consisting of rows and columns) of floats based on arguments provided by the user to determine the dimensions of the array, but that the content will consist of floats that range between 0 to 0.99 (i.e. up to but not including 1), in a [uniform distribution](https://www.investopedia.com/terms/u/uniform-distribution.asp) (which means that the probability of all outcomes have exactly the same possibility of happening). 

In [1]:
import numpy as np
np.random.rand(4,3)

array([[0.99008575, 0.58945044, 0.51110391],
       [0.44520501, 0.11830076, 0.13695848],
       [0.87743011, 0.83914703, 0.55021243],
       [0.50564006, 0.54577821, 0.04276217]])

I can see from the above that an array of 4 rows and 3 columns has been printed, all with randomly selected numbers that actally range from 0 to 0.99999999 (8 decimal places - floating point??)

While reading numpy.random online I found a [blog post](http://www.learningaboutelectronics.com/Articles/How-to-create-an-array-of-random-integers-in-Python-with-numpy.php) that gave an introduction to the submodule and then detailed how to create an array of 5 random integers between 1 and 100:

In [8]:
import numpy as np
#creates an array of 5 random integers from 1 too 100
np.random.randint(1,101,5)

array([20,  5, 16, 33, 88])

I noticed that the arguments passed through this function were 1 and 101, not 100, as this command follows standard Python practice of indexing from 0.
Using this blog's suggested array as a basis for further testing, I listed through the rest of the commands in the Simple Random Data *category* as follows:

In [11]:
np.random.randn(1,101,5)

#the function np.random.integers has been deprecated and replaced with the above np.random.randint

array([[[ 1.86860234e+00,  9.94621902e-01, -1.12737410e+00,
          4.30556595e-01,  3.18414783e-02],
        [ 1.88930681e+00,  2.69561689e-03, -5.90648825e-01,
          9.34877364e-01,  1.28549737e+00],
        [ 2.51260012e-01,  6.70226164e-02, -8.40802230e-01,
          1.49711191e+00,  3.79994052e-01],
        [-1.66223999e+00,  7.13969310e-01, -2.51210110e-01,
          2.41925852e-01, -3.87361910e-01],
        [-1.37010410e+00,  1.60473304e+00, -5.31051243e-01,
          7.63229590e-03,  2.87968633e+00],
        [ 9.62038800e-01,  2.20390979e-01, -1.01468596e-01,
          8.86600404e-01, -6.84371643e-01],
        [ 1.98620875e+00,  1.26771846e+00,  1.06732545e+00,
         -1.48333728e+00, -6.68933066e-01],
        [-8.57397852e-01, -2.16134406e+00,  1.39135261e+00,
          3.99033879e-01,  4.80061674e-01],
        [ 1.29822823e+00, -2.25157485e-01,  1.36297763e+00,
         -5.48886266e-01,  6.49374572e-01],
        [-7.95434003e-01,  7.11245868e-01,  1.80257365e-01,
    

## Permutations
The Permutations functions of numpy.random are [shuffle(x)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.shuffle.html) and [permutation(x)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.permutation.html#numpy.random.permutation).  

Both of these functions relate to re-arranging provided random data. The shuffle(x) function shuffles data on the first axis of a multi-dimensional array, where the order of sub-arrays is changed but the contents remain the same:


### Multi Dimensional Array

In [4]:
#example from https://www.science-emergence.com/Articles/How-to-randomly-shuffle-an-array-in-python-using-numpy/ 
import numpy as np
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.random.shuffle(M)
M

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

As you can see above, the sequence that the sets are displayed in has been shuffled, but the numbers inside the brackets have remained in the same order they were originally written in.

### 1 Dimensional Array
With an array that is 1 Dimensional, the shuffle(x) function 

In [5]:
#example from https://www.science-emergence.com/Articles/How-to-randomly-shuffle-an-array-in-python-using-numpy/ 
import numpy as np
M = np.array([4,8,15,16,23,42])
np.random.shuffle(M)
M

array([ 4, 15, 42,  8, 23, 16])

As you can see above, the sequence that the sets are displayed in has been shuffled, but the contents inside the brackets have remained in the same order.

The permutation(x) function however, when given an array, takes a copy and shuffles the elements randomly. 

In [6]:
#example using an array from https://www.w3cschool.cn/doc_numpy_1_10/numpy_1_10-generated-numpy-random-permutation.html
import numpy as np
array = np.random.permutation([1, 4, 9, 12, 15])
array

array([ 9, 12,  4, 15,  1])

In the case of an integer, the permutation function randomly permutes it's range:

In [7]:
#example using an integer 
import numpy as np
integer = np.random.permutation(8)
integer

array([0, 5, 1, 7, 6, 3, 2, 4])